spring:
  datasource:
    url: jdbc:mysql://47.92.133.46:3306/tax_bureau?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
qrCode:
  #  餐厅
  reQrUrl: http://39.108.118.48:8080/tax-service/v1/qrCode/restaurantQrCode
  restaurantQrCode: http://www.baidu.com
  #  超市
  suQrUrl: http://39.108.118.48:8080/tax-service/v1/qrCode/supermarketQrCode
  supermarketQrCode: http://www.baidu.com
  #  建材
  buQrUrl: http://39.108.118.48:8080/tax-service/v1/qrCode/buildingMaterialQrCode
  buildingMaterialQrCode: http://www.baidu.com
  #  管理员
  admin: http://www.baidu.com
  #  操作员
  operator: http://www.baidu.com
  #  用户
  user: http://192.168.10.176:8080
# 图片上传到本工程服务器
file:
  url: http://39.108.118.48:8080/tax-service
# 调微信支付接口的账号密码
wx:
  userName: 20200411200848698625624062988288
  passWord: d7cef41ed7324e8393a2f8967669cdeb
# 相关微信接口
  authLogin: http://39.108.118.48:8080/dkm_pay_resource/v1/auth/authLogin
  payToPerson: http://39.108.118.48:8080/dkm_pay_resource/v1/wxPay/toPerson

