spring:
  datasource:
    url: jdbc:mysql://47.92.133.46:3306/tax_bureau?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

